formatting updates

diff --git a/upgrade b/upgrade
--- a/upgrade
+++ b/upgrade
@@ -436,11 +436,11 @@ for file in "${disable_svc[@]}" ; do
 #	status=$(systemctl status "${file}" 2>/dev/null | grep Loaded: | grep -o "disabled")
 	if [ "${ups_type}" == "none" ] && [ "${file}" == "ser2net.service" ] && [ "${status}" != "enabled" ]; then
 		printf " Status of ${yel}${file}${nor} is currently ${drk_red}${status}${nor}..."
-		systemctl enable "${file}"  2>/dev/null && printf " ${drk_grn}Enabled${nor}.\n" || printf " ${drk_red}Failed to enable${nor}.\n"
+		systemctl enable "${file}"  2>/dev/null && printf "${drk_grn}Enabled${nor}.\n" || printf "${drk_red}Failed to enable${nor}.\n"
 	else
 		if [ "${status}" != "disabled" ] && [ "${status}" != "static" ]; then
 			printf " Status of ${yel}${file}${nor} is currently ${drk_red}${status}${nor}..."
-			systemctl disable "${file}"  2>/dev/null && printf " ${drk_grn}Disabeled${nor}.\n" || printf " ${drk_red}Failed to disable${nor}.\n"
+			systemctl disable "${file}"  2>/dev/null && printf "${drk_grn}Disabeled${nor}.\n" || printf "${drk_red}Failed to disable${nor}.\n"
 		else
 			printf " Status of ${yel}${file}${nor} is currently ${drk_grn}${status}${nor}.\n"
 	fi	fi
@@ -518,7 +518,7 @@ fi
 		if cmp --silent "${etc_folder}${file}" "${project_folder}${file}" ; then
 			printf " ${nor}Both versions of ${yel}${file} ${nor}are the same, Skipping...\n"
 		else
-			cp ${project_folder}${file} ${etc_folder} && printf " ${yel}${file} ${nor}copied.\n" || break
+			cp ${project_folder}${file} ${etc_folder} && printf "${yel}${file} ${nor}copied.\n" || break
 		fi
 	done
 
